# general settings for image SR training
name: ART_S_SR_x3
model_type: ARTModel
scale: 3
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/HR
    dataroot_lq: datasets/DF2K/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/SR/Set5/HR
    dataroot_lq: datasets/SR/Set5/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

# network structures
network_g:
  type: ART
  upscale: 3
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  interval: [8, 8, 8, 8, 8, 8]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: experiments/pretrained_models/SR_ART_S_x2.pth # save training time if we finetune from x2 and halve initial lr.
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    # lr: !!float 2e-4
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    # milestones: [ 250000, 400000, 450000, 475000 ]
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  # total_iter: 500000
  total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: true



# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500